
package com.montivero.poc.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PizzaSoapService", targetNamespace = "http://service.poc.montivero.com/", wsdlLocation = "http://localhost:9999/pizzaService?wsdl")
public class PizzaSoapService
    extends Service
{

    private final static URL PIZZASOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException PIZZASOAPSERVICE_EXCEPTION;
    private final static QName PIZZASOAPSERVICE_QNAME = new QName("http://service.poc.montivero.com/", "PizzaSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/pizzaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PIZZASOAPSERVICE_WSDL_LOCATION = url;
        PIZZASOAPSERVICE_EXCEPTION = e;
    }

    public PizzaSoapService() {
        super(__getWsdlLocation(), PIZZASOAPSERVICE_QNAME);
    }

    public PizzaSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PIZZASOAPSERVICE_QNAME, features);
    }

    public PizzaSoapService(URL wsdlLocation) {
        super(wsdlLocation, PIZZASOAPSERVICE_QNAME);
    }

    public PizzaSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PIZZASOAPSERVICE_QNAME, features);
    }

    public PizzaSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PizzaSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PizzaSoap
     */
    @WebEndpoint(name = "PizzaSoapPort")
    public PizzaSoap getPizzaSoapPort() {
        return super.getPort(new QName("http://service.poc.montivero.com/", "PizzaSoapPort"), PizzaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PizzaSoap
     */
    @WebEndpoint(name = "PizzaSoapPort")
    public PizzaSoap getPizzaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.poc.montivero.com/", "PizzaSoapPort"), PizzaSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PIZZASOAPSERVICE_EXCEPTION!= null) {
            throw PIZZASOAPSERVICE_EXCEPTION;
        }
        return PIZZASOAPSERVICE_WSDL_LOCATION;
    }

}
